/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CiltBakimiRouteImport } from './routes/cilt-bakimi'
import { Route as DovmeSilmeRouteImport } from './routes/dovme-silme'
import { Route as ErkekLazerEpilasyonRouteImport } from './routes/erkek-lazer-epilasyon'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as IpekKirpikRouteImport } from './routes/ipek-kirpik'
import { Route as KaliciMakyajRouteImport } from './routes/kalici-makyaj'
import { Route as KampanyaRouteImport } from './routes/kampanya'
import { Route as KarbonPeelingRouteImport } from './routes/karbon-peeling'
import { Route as KeratinBrezilyaFonuRouteImport } from './routes/keratin-brezilya-fonu'
import { Route as KuaforRouteImport } from './routes/kuafor'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as LazerEpilasyonRouteImport } from './routes/lazer-epilasyon'
import { Route as ProtezSacRouteImport } from './routes/protez-sac'
import { Route as ProtezTirnakRouteImport } from './routes/protez-tirnak'
import { Route as ReformerPilatesRouteImport } from './routes/reformer-pilates'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SacBoyamaRouteImport } from './routes/sac-boyama'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VucutSekillendirmeRouteImport } from './routes/vucut-sekillendirme'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as UploadsSplatRouteImport } from './routes/uploads.$'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin_.blog'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin_.gallery'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin_.blog_.$id'
import { Route as AuthenticatedAdminBlogNewRouteImport } from './routes/_authenticated/admin_.blog_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CiltBakimiRoute = CiltBakimiRouteImport.update({
  id: '/cilt-bakimi',
  path: '/cilt-bakimi',
  getParentRoute: () => rootRouteImport,
} as any)
const DovmeSilmeRoute = DovmeSilmeRouteImport.update({
  id: '/dovme-silme',
  path: '/dovme-silme',
  getParentRoute: () => rootRouteImport,
} as any)
const ErkekLazerEpilasyonRoute = ErkekLazerEpilasyonRouteImport.update({
  id: '/erkek-lazer-epilasyon',
  path: '/erkek-lazer-epilasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const IpekKirpikRoute = IpekKirpikRouteImport.update({
  id: '/ipek-kirpik',
  path: '/ipek-kirpik',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliciMakyajRoute = KaliciMakyajRouteImport.update({
  id: '/kalici-makyaj',
  path: '/kalici-makyaj',
  getParentRoute: () => rootRouteImport,
} as any)
const KampanyaRoute = KampanyaRouteImport.update({
  id: '/kampanya',
  path: '/kampanya',
  getParentRoute: () => rootRouteImport,
} as any)
const KarbonPeelingRoute = KarbonPeelingRouteImport.update({
  id: '/karbon-peeling',
  path: '/karbon-peeling',
  getParentRoute: () => rootRouteImport,
} as any)
const KeratinBrezilyaFonuRoute = KeratinBrezilyaFonuRouteImport.update({
  id: '/keratin-brezilya-fonu',
  path: '/keratin-brezilya-fonu',
  getParentRoute: () => rootRouteImport,
} as any)
const KuaforRoute = KuaforRouteImport.update({
  id: '/kuafor',
  path: '/kuafor',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const LazerEpilasyonRoute = LazerEpilasyonRouteImport.update({
  id: '/lazer-epilasyon',
  path: '/lazer-epilasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtezSacRoute = ProtezSacRouteImport.update({
  id: '/protez-sac',
  path: '/protez-sac',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtezTirnakRoute = ProtezTirnakRouteImport.update({
  id: '/protez-tirnak',
  path: '/protez-tirnak',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformerPilatesRoute = ReformerPilatesRouteImport.update({
  id: '/reformer-pilates',
  path: '/reformer-pilates',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SacBoyamaRoute = SacBoyamaRouteImport.update({
  id: '/sac-boyama',
  path: '/sac-boyama',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VucutSekillendirmeRoute = VucutSekillendirmeRouteImport.update({
  id: '/vucut-sekillendirme',
  path: '/vucut-sekillendirme',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/admin_/blog',
  path: '/admin/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/admin_/gallery',
    path: '/admin/gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/admin_/blog_/$id',
    path: '/admin/blog/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogNewRoute =
  AuthenticatedAdminBlogNewRouteImport.update({
    id: '/admin_/blog_/new',
    path: '/admin/blog/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cilt-bakimi': typeof CiltBakimiRoute
  '/dovme-silme': typeof DovmeSilmeRoute
  '/erkek-lazer-epilasyon': typeof ErkekLazerEpilasyonRoute
  '/galeri': typeof GaleriRoute
  '/hizmetler': typeof HizmetlerRoute
  '/ipek-kirpik': typeof IpekKirpikRoute
  '/kalici-makyaj': typeof KaliciMakyajRoute
  '/kampanya': typeof KampanyaRoute
  '/karbon-peeling': typeof KarbonPeelingRoute
  '/keratin-brezilya-fonu': typeof KeratinBrezilyaFonuRoute
  '/kuafor': typeof KuaforRoute
  '/kvkk': typeof KvkkRoute
  '/lazer-epilasyon': typeof LazerEpilasyonRoute
  '/protez-sac': typeof ProtezSacRoute
  '/protez-tirnak': typeof ProtezTirnakRoute
  '/reformer-pilates': typeof ReformerPilatesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sac-boyama': typeof SacBoyamaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vucut-sekillendirme': typeof VucutSekillendirmeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cilt-bakimi': typeof CiltBakimiRoute
  '/dovme-silme': typeof DovmeSilmeRoute
  '/erkek-lazer-epilasyon': typeof ErkekLazerEpilasyonRoute
  '/galeri': typeof GaleriRoute
  '/hizmetler': typeof HizmetlerRoute
  '/ipek-kirpik': typeof IpekKirpikRoute
  '/kalici-makyaj': typeof KaliciMakyajRoute
  '/kampanya': typeof KampanyaRoute
  '/karbon-peeling': typeof KarbonPeelingRoute
  '/keratin-brezilya-fonu': typeof KeratinBrezilyaFonuRoute
  '/kuafor': typeof KuaforRoute
  '/kvkk': typeof KvkkRoute
  '/lazer-epilasyon': typeof LazerEpilasyonRoute
  '/protez-sac': typeof ProtezSacRoute
  '/protez-tirnak': typeof ProtezTirnakRoute
  '/reformer-pilates': typeof ReformerPilatesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sac-boyama': typeof SacBoyamaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vucut-sekillendirme': typeof VucutSekillendirmeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cilt-bakimi': typeof CiltBakimiRoute
  '/dovme-silme': typeof DovmeSilmeRoute
  '/erkek-lazer-epilasyon': typeof ErkekLazerEpilasyonRoute
  '/galeri': typeof GaleriRoute
  '/hizmetler': typeof HizmetlerRoute
  '/ipek-kirpik': typeof IpekKirpikRoute
  '/kalici-makyaj': typeof KaliciMakyajRoute
  '/kampanya': typeof KampanyaRoute
  '/karbon-peeling': typeof KarbonPeelingRoute
  '/keratin-brezilya-fonu': typeof KeratinBrezilyaFonuRoute
  '/kuafor': typeof KuaforRoute
  '/kvkk': typeof KvkkRoute
  '/lazer-epilasyon': typeof LazerEpilasyonRoute
  '/protez-sac': typeof ProtezSacRoute
  '/protez-tirnak': typeof ProtezTirnakRoute
  '/reformer-pilates': typeof ReformerPilatesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sac-boyama': typeof SacBoyamaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vucut-sekillendirme': typeof VucutSekillendirmeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/_authenticated/admin_/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin_/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin_/blog_/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin_/blog_/new': typeof AuthenticatedAdminBlogNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/cilt-bakimi'
    | '/dovme-silme'
    | '/erkek-lazer-epilasyon'
    | '/galeri'
    | '/hizmetler'
    | '/ipek-kirpik'
    | '/kalici-makyaj'
    | '/kampanya'
    | '/karbon-peeling'
    | '/keratin-brezilya-fonu'
    | '/kuafor'
    | '/kvkk'
    | '/lazer-epilasyon'
    | '/protez-sac'
    | '/protez-tirnak'
    | '/reformer-pilates'
    | '/robots.txt'
    | '/sac-boyama'
    | '/sitemap.xml'
    | '/vucut-sekillendirme'
    | '/admin'
    | '/blog/$slug'
    | '/uploads/$'
    | '/admin/blog'
    | '/admin/gallery'
    | '/admin/blog/$id'
    | '/admin/blog/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/cilt-bakimi'
    | '/dovme-silme'
    | '/erkek-lazer-epilasyon'
    | '/galeri'
    | '/hizmetler'
    | '/ipek-kirpik'
    | '/kalici-makyaj'
    | '/kampanya'
    | '/karbon-peeling'
    | '/keratin-brezilya-fonu'
    | '/kuafor'
    | '/kvkk'
    | '/lazer-epilasyon'
    | '/protez-sac'
    | '/protez-tirnak'
    | '/reformer-pilates'
    | '/robots.txt'
    | '/sac-boyama'
    | '/sitemap.xml'
    | '/vucut-sekillendirme'
    | '/admin'
    | '/blog/$slug'
    | '/uploads/$'
    | '/admin/blog'
    | '/admin/gallery'
    | '/admin/blog/$id'
    | '/admin/blog/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/cilt-bakimi'
    | '/dovme-silme'
    | '/erkek-lazer-epilasyon'
    | '/galeri'
    | '/hizmetler'
    | '/ipek-kirpik'
    | '/kalici-makyaj'
    | '/kampanya'
    | '/karbon-peeling'
    | '/keratin-brezilya-fonu'
    | '/kuafor'
    | '/kvkk'
    | '/lazer-epilasyon'
    | '/protez-sac'
    | '/protez-tirnak'
    | '/reformer-pilates'
    | '/robots.txt'
    | '/sac-boyama'
    | '/sitemap.xml'
    | '/vucut-sekillendirme'
    | '/_authenticated/admin'
    | '/blog_/$slug'
    | '/uploads/$'
    | '/_authenticated/admin_/blog'
    | '/_authenticated/admin_/gallery'
    | '/_authenticated/admin_/blog_/$id'
    | '/_authenticated/admin_/blog_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CiltBakimiRoute: typeof CiltBakimiRoute
  DovmeSilmeRoute: typeof DovmeSilmeRoute
  ErkekLazerEpilasyonRoute: typeof ErkekLazerEpilasyonRoute
  GaleriRoute: typeof GaleriRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IpekKirpikRoute: typeof IpekKirpikRoute
  KaliciMakyajRoute: typeof KaliciMakyajRoute
  KampanyaRoute: typeof KampanyaRoute
  KarbonPeelingRoute: typeof KarbonPeelingRoute
  KeratinBrezilyaFonuRoute: typeof KeratinBrezilyaFonuRoute
  KuaforRoute: typeof KuaforRoute
  KvkkRoute: typeof KvkkRoute
  LazerEpilasyonRoute: typeof LazerEpilasyonRoute
  ProtezSacRoute: typeof ProtezSacRoute
  ProtezTirnakRoute: typeof ProtezTirnakRoute
  ReformerPilatesRoute: typeof ReformerPilatesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SacBoyamaRoute: typeof SacBoyamaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VucutSekillendirmeRoute: typeof VucutSekillendirmeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cilt-bakimi': {
      id: '/cilt-bakimi'
      path: '/cilt-bakimi'
      fullPath: '/cilt-bakimi'
      preLoaderRoute: typeof CiltBakimiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dovme-silme': {
      id: '/dovme-silme'
      path: '/dovme-silme'
      fullPath: '/dovme-silme'
      preLoaderRoute: typeof DovmeSilmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erkek-lazer-epilasyon': {
      id: '/erkek-lazer-epilasyon'
      path: '/erkek-lazer-epilasyon'
      fullPath: '/erkek-lazer-epilasyon'
      preLoaderRoute: typeof ErkekLazerEpilasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipek-kirpik': {
      id: '/ipek-kirpik'
      path: '/ipek-kirpik'
      fullPath: '/ipek-kirpik'
      preLoaderRoute: typeof IpekKirpikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalici-makyaj': {
      id: '/kalici-makyaj'
      path: '/kalici-makyaj'
      fullPath: '/kalici-makyaj'
      preLoaderRoute: typeof KaliciMakyajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampanya': {
      id: '/kampanya'
      path: '/kampanya'
      fullPath: '/kampanya'
      preLoaderRoute: typeof KampanyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karbon-peeling': {
      id: '/karbon-peeling'
      path: '/karbon-peeling'
      fullPath: '/karbon-peeling'
      preLoaderRoute: typeof KarbonPeelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keratin-brezilya-fonu': {
      id: '/keratin-brezilya-fonu'
      path: '/keratin-brezilya-fonu'
      fullPath: '/keratin-brezilya-fonu'
      preLoaderRoute: typeof KeratinBrezilyaFonuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuafor': {
      id: '/kuafor'
      path: '/kuafor'
      fullPath: '/kuafor'
      preLoaderRoute: typeof KuaforRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lazer-epilasyon': {
      id: '/lazer-epilasyon'
      path: '/lazer-epilasyon'
      fullPath: '/lazer-epilasyon'
      preLoaderRoute: typeof LazerEpilasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protez-sac': {
      id: '/protez-sac'
      path: '/protez-sac'
      fullPath: '/protez-sac'
      preLoaderRoute: typeof ProtezSacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protez-tirnak': {
      id: '/protez-tirnak'
      path: '/protez-tirnak'
      fullPath: '/protez-tirnak'
      preLoaderRoute: typeof ProtezTirnakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reformer-pilates': {
      id: '/reformer-pilates'
      path: '/reformer-pilates'
      fullPath: '/reformer-pilates'
      preLoaderRoute: typeof ReformerPilatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sac-boyama': {
      id: '/sac-boyama'
      path: '/sac-boyama'
      fullPath: '/sac-boyama'
      preLoaderRoute: typeof SacBoyamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vucut-sekillendirme': {
      id: '/vucut-sekillendirme'
      path: '/vucut-sekillendirme'
      fullPath: '/vucut-sekillendirme'
      preLoaderRoute: typeof VucutSekillendirmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/blog': {
      id: '/_authenticated/admin_/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/gallery': {
      id: '/_authenticated/admin_/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/blog_/$id': {
      id: '/_authenticated/admin_/blog_/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/blog_/new': {
      id: '/_authenticated/admin_/blog_/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogNewRoute: typeof AuthenticatedAdminBlogNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
  AuthenticatedAdminBlogNewRoute: AuthenticatedAdminBlogNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CiltBakimiRoute: CiltBakimiRoute,
  DovmeSilmeRoute: DovmeSilmeRoute,
  ErkekLazerEpilasyonRoute: ErkekLazerEpilasyonRoute,
  GaleriRoute: GaleriRoute,
  HizmetlerRoute: HizmetlerRoute,
  IpekKirpikRoute: IpekKirpikRoute,
  KaliciMakyajRoute: KaliciMakyajRoute,
  KampanyaRoute: KampanyaRoute,
  KarbonPeelingRoute: KarbonPeelingRoute,
  KeratinBrezilyaFonuRoute: KeratinBrezilyaFonuRoute,
  KuaforRoute: KuaforRoute,
  KvkkRoute: KvkkRoute,
  LazerEpilasyonRoute: LazerEpilasyonRoute,
  ProtezSacRoute: ProtezSacRoute,
  ProtezTirnakRoute: ProtezTirnakRoute,
  ReformerPilatesRoute: ReformerPilatesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SacBoyamaRoute: SacBoyamaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VucutSekillendirmeRoute: VucutSekillendirmeRoute,
  BlogSlugRoute: BlogSlugRoute,
  UploadsSplatRoute: UploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
