/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CiltBakimiRouteImport } from './routes/cilt-bakimi'
import { Route as DovmeSilmeRouteImport } from './routes/dovme-silme'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as KaliciMakyajRouteImport } from './routes/kalici-makyaj'
import { Route as KampanyaRouteImport } from './routes/kampanya'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as LazerEpilasyonRouteImport } from './routes/lazer-epilasyon'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VucutSekillendirmeRouteImport } from './routes/vucut-sekillendirme'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as UploadsSplatRouteImport } from './routes/uploads.$'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin_.blog'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin_.gallery'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin_.blog_.$id'
import { Route as AuthenticatedAdminBlogNewRouteImport } from './routes/_authenticated/admin_.blog_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CiltBakimiRoute = CiltBakimiRouteImport.update({
  id: '/cilt-bakimi',
  path: '/cilt-bakimi',
  getParentRoute: () => rootRouteImport,
} as any)
const DovmeSilmeRoute = DovmeSilmeRouteImport.update({
  id: '/dovme-silme',
  path: '/dovme-silme',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliciMakyajRoute = KaliciMakyajRouteImport.update({
  id: '/kalici-makyaj',
  path: '/kalici-makyaj',
  getParentRoute: () => rootRouteImport,
} as any)
const KampanyaRoute = KampanyaRouteImport.update({
  id: '/kampanya',
  path: '/kampanya',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const LazerEpilasyonRoute = LazerEpilasyonRouteImport.update({
  id: '/lazer-epilasyon',
  path: '/lazer-epilasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VucutSekillendirmeRoute = VucutSekillendirmeRouteImport.update({
  id: '/vucut-sekillendirme',
  path: '/vucut-sekillendirme',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/admin_/blog',
  path: '/admin/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/admin_/gallery',
    path: '/admin/gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/admin_/blog_/$id',
    path: '/admin/blog/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogNewRoute =
  AuthenticatedAdminBlogNewRouteImport.update({
    id: '/admin_/blog_/new',
    path: '/admin/blog/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cilt-bakimi': typeof CiltBakimiRoute
  '/dovme-silme': typeof DovmeSilmeRoute
  '/galeri': typeof GaleriRoute
  '/kalici-makyaj': typeof KaliciMakyajRoute
  '/kampanya': typeof KampanyaRoute
  '/kvkk': typeof KvkkRoute
  '/lazer-epilasyon': typeof LazerEpilasyonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vucut-sekillendirme': typeof VucutSekillendirmeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cilt-bakimi': typeof CiltBakimiRoute
  '/dovme-silme': typeof DovmeSilmeRoute
  '/galeri': typeof GaleriRoute
  '/kalici-makyaj': typeof KaliciMakyajRoute
  '/kampanya': typeof KampanyaRoute
  '/kvkk': typeof KvkkRoute
  '/lazer-epilasyon': typeof LazerEpilasyonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vucut-sekillendirme': typeof VucutSekillendirmeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cilt-bakimi': typeof CiltBakimiRoute
  '/dovme-silme': typeof DovmeSilmeRoute
  '/galeri': typeof GaleriRoute
  '/kalici-makyaj': typeof KaliciMakyajRoute
  '/kampanya': typeof KampanyaRoute
  '/kvkk': typeof KvkkRoute
  '/lazer-epilasyon': typeof LazerEpilasyonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vucut-sekillendirme': typeof VucutSekillendirmeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/_authenticated/admin_/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin_/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin_/blog_/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin_/blog_/new': typeof AuthenticatedAdminBlogNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/cilt-bakimi'
    | '/dovme-silme'
    | '/galeri'
    | '/kalici-makyaj'
    | '/kampanya'
    | '/kvkk'
    | '/lazer-epilasyon'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/vucut-sekillendirme'
    | '/admin'
    | '/blog/$slug'
    | '/uploads/$'
    | '/admin/blog'
    | '/admin/gallery'
    | '/admin/blog/$id'
    | '/admin/blog/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/cilt-bakimi'
    | '/dovme-silme'
    | '/galeri'
    | '/kalici-makyaj'
    | '/kampanya'
    | '/kvkk'
    | '/lazer-epilasyon'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/vucut-sekillendirme'
    | '/admin'
    | '/blog/$slug'
    | '/uploads/$'
    | '/admin/blog'
    | '/admin/gallery'
    | '/admin/blog/$id'
    | '/admin/blog/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/cilt-bakimi'
    | '/dovme-silme'
    | '/galeri'
    | '/kalici-makyaj'
    | '/kampanya'
    | '/kvkk'
    | '/lazer-epilasyon'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/vucut-sekillendirme'
    | '/_authenticated/admin'
    | '/blog_/$slug'
    | '/uploads/$'
    | '/_authenticated/admin_/blog'
    | '/_authenticated/admin_/gallery'
    | '/_authenticated/admin_/blog_/$id'
    | '/_authenticated/admin_/blog_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CiltBakimiRoute: typeof CiltBakimiRoute
  DovmeSilmeRoute: typeof DovmeSilmeRoute
  GaleriRoute: typeof GaleriRoute
  KaliciMakyajRoute: typeof KaliciMakyajRoute
  KampanyaRoute: typeof KampanyaRoute
  KvkkRoute: typeof KvkkRoute
  LazerEpilasyonRoute: typeof LazerEpilasyonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VucutSekillendirmeRoute: typeof VucutSekillendirmeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cilt-bakimi': {
      id: '/cilt-bakimi'
      path: '/cilt-bakimi'
      fullPath: '/cilt-bakimi'
      preLoaderRoute: typeof CiltBakimiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dovme-silme': {
      id: '/dovme-silme'
      path: '/dovme-silme'
      fullPath: '/dovme-silme'
      preLoaderRoute: typeof DovmeSilmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalici-makyaj': {
      id: '/kalici-makyaj'
      path: '/kalici-makyaj'
      fullPath: '/kalici-makyaj'
      preLoaderRoute: typeof KaliciMakyajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampanya': {
      id: '/kampanya'
      path: '/kampanya'
      fullPath: '/kampanya'
      preLoaderRoute: typeof KampanyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lazer-epilasyon': {
      id: '/lazer-epilasyon'
      path: '/lazer-epilasyon'
      fullPath: '/lazer-epilasyon'
      preLoaderRoute: typeof LazerEpilasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vucut-sekillendirme': {
      id: '/vucut-sekillendirme'
      path: '/vucut-sekillendirme'
      fullPath: '/vucut-sekillendirme'
      preLoaderRoute: typeof VucutSekillendirmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/blog': {
      id: '/_authenticated/admin_/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/gallery': {
      id: '/_authenticated/admin_/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/blog_/$id': {
      id: '/_authenticated/admin_/blog_/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/blog_/new': {
      id: '/_authenticated/admin_/blog_/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogNewRoute: typeof AuthenticatedAdminBlogNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
  AuthenticatedAdminBlogNewRoute: AuthenticatedAdminBlogNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CiltBakimiRoute: CiltBakimiRoute,
  DovmeSilmeRoute: DovmeSilmeRoute,
  GaleriRoute: GaleriRoute,
  KaliciMakyajRoute: KaliciMakyajRoute,
  KampanyaRoute: KampanyaRoute,
  KvkkRoute: KvkkRoute,
  LazerEpilasyonRoute: LazerEpilasyonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VucutSekillendirmeRoute: VucutSekillendirmeRoute,
  BlogSlugRoute: BlogSlugRoute,
  UploadsSplatRoute: UploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
